import type { GeoLocation, Offer, Vehicle } from "./types";

export const VEHICLES: Vehicle[] = [
  {
    id: "206-t5",
    make: "پژو",
    model: "۲۰۶",
    trim: "تیپ ۵",
    year: "۱۳۸۹",
    engine: "TU5",
  },
  {
    id: "206-t2",
    make: "پژو",
    model: "۲۰۶",
    trim: "تیپ ۲",
    year: "۱۳۸۶",
    engine: "TU3",
  },
  {
    id: "pride-131",
    make: "پراید",
    model: "۱۳۱",
    trim: "SE",
    year: "۱۳۹۲",
    engine: "M13",
  },
  {
    id: "samand-lx",
    make: "سمند",
    model: "LX",
    trim: "EF7",
    year: "۱۳۹۴",
    engine: "EF7",
  },
];

export const LOCATIONS: GeoLocation[] = [
  {
    id: "punak",
    label: "تهران، پونک",
    city: "تهران",
    neighborhood: "پونک",
    source: "gps",
  },
  {
    id: "valiasr",
    label: "تهران، ولیعصر",
    city: "تهران",
    neighborhood: "ولیعصر",
    source: "manual",
  },
  {
    id: "enghelab",
    label: "تهران، انقلاب",
    city: "تهران",
    neighborhood: "انقلاب",
    source: "manual",
  },
  {
    id: "karaj",
    label: "کرج، گوهردشت",
    city: "کرج",
    neighborhood: "گوهردشت",
    source: "ip",
  },
];

export const SEARCH_QUERY = "دیسک صفحه ۲۰۶ تیپ ۵";

export const OFFERS: Offer[] = [
  {
    id: "o1",
    title: "کیت کلاچ والئو PHC با بلبرینگ",
    brand: "Valeo PHC",
    origin: "oem",
    oemCode: "۸۲۶۲۱۱",
    price: 14_500_000,
    image: "/parts/workshop.jpg",
    photoKind: "seller",
    vehicleIds: ["206-t5"],
    seller: {
      id: "s-arya",
      name: "آریا یدکی پونک",
      rating: 4.8,
      reviewCount: 214,
      neighborhood: "پونک",
      city: "تهران",
      distanceKm: 1.2,
      channel: "hybrid",
      hours: "۹ تا ۲۱",
      phone: "۰۲۱۴۴۳۲۱۸۹۰",
      hasInstallments: true,
      torobGuarantee: true,
      stock: "now",
      responseMins: 8,
    },
    deliveryHours: 2,
    actions: ["buy", "call", "nav", "chat"],
  },
  {
    id: "o2",
    title: "دیسک و صفحه والئو مناسب تیپ ۵",
    brand: "Valeo",
    origin: "oem",
    oemCode: "۸۲۶۲۱۱",
    price: 16_100_000,
    image: "/parts/shop-shelf.jpg",
    photoKind: "seller",
    vehicleIds: ["206-t5"],
    seller: {
      id: "s-valiasr",
      name: "اتوپارت ولیعصر",
      rating: 4.9,
      reviewCount: 88,
      neighborhood: "ولیعصر",
      city: "تهران",
      distanceKm: 0.8,
      channel: "physical",
      hours: "۱۰ تا ۲۰",
      phone: "۰۲۱۸۸۹۹۱۲۰۰",
      hasInstallments: false,
      torobGuarantee: true,
      stock: "now",
      responseMins: 4,
    },
    deliveryHours: 0,
    actions: ["call", "nav", "chat"],
  },
  {
    id: "o3",
    title: "دیسک و صفحه پژو ۲۰۶ تیپ ۵ والئو آبی",
    brand: "Valeo PHC",
    origin: "oem",
    price: 14_800_000,
    image: "/parts/valeo-box.jpg",
    photoKind: "catalog",
    vehicleIds: ["206-t5", "206-t2"],
    seller: {
      id: "s-hami",
      name: "طهران حامی پارت",
      rating: 4.6,
      reviewCount: 51,
      neighborhood: "صادقیه",
      city: "تهران",
      distanceKm: 5.1,
      channel: "hybrid",
      hours: "۹ تا ۱۸",
      phone: "۰۲۱۴۴۰۰۷۷۱۱",
      hasInstallments: true,
      torobGuarantee: false,
      stock: "now",
      responseMins: 25,
    },
    deliveryHours: 6,
    actions: ["buy", "call", "nav"],
  },
  {
    id: "o4",
    title: "کیت کلاچ کامل ۲۰۶",
    brand: "Valeo",
    origin: "oem",
    price: 15_200_000,
    image: "/parts/kit-open.jpg",
    photoKind: "catalog",
    vehicleIds: ["206-t5"],
    seller: {
      id: "s-clutch",
      name: "کلاچ سنتر صادقیه",
      rating: 4.7,
      reviewCount: 120,
      neighborhood: "صادقیه",
      city: "تهران",
      distanceKm: 2.1,
      channel: "physical",
      hours: "۸ تا ۱۹",
      phone: "۰۲۱۴۴۲۲۶۶۵۵",
      hasInstallments: false,
      torobGuarantee: false,
      stock: "now",
      responseMins: 12,
    },
    actions: ["call", "nav", "chat"],
  },
  {
    id: "o5",
    title: "دیسک و صفحه طرح اقتصادی ۲۰۶",
    brand: "متفرقه",
    origin: "aftermarket",
    price: 12_200_000,
    image: "/parts/aftermarket.jpg",
    photoKind: "catalog",
    vehicleIds: ["206-t5", "206-t2"],
    seller: {
      id: "s-pars",
      name: "یدکی آنلاین پارس",
      rating: 4.1,
      reviewCount: 890,
      neighborhood: "انبار مرکزی",
      city: "تهران",
      distanceKm: null,
      channel: "online",
      hasInstallments: false,
      torobGuarantee: false,
      stock: "now",
      responseMins: 40,
    },
    deliveryHours: 36,
    actions: ["buy", "chat"],
  },
  {
    id: "o6",
    title: "دیسک و صفحه کلاچ والئو مناسب پژو ۲۰۶ تیپ ۵",
    brand: "Valeo",
    origin: "oem",
    oemCode: "۸۲۶۲۱۱",
    price: 18_900_000,
    image: "/parts/green-kit.jpg",
    photoKind: "catalog",
    vehicleIds: ["206-t5"],
    isAd: true,
    seller: {
      id: "s-rad",
      name: "مستر باک راد",
      rating: 4.2,
      reviewCount: 19,
      neighborhood: "تهرانپارس",
      city: "تهران",
      distanceKm: 14.6,
      channel: "online",
      hasInstallments: true,
      torobGuarantee: false,
      stock: "limited",
      responseMins: 90,
    },
    deliveryHours: 48,
    actions: ["buy"],
  },
  {
    id: "o7",
    title: "کیت کلاچ ۲۰۶ با گارانتی تعویض",
    brand: "ISC",
    origin: "aftermarket",
    price: 13_900_000,
    image: "/parts/disc.jpg",
    photoKind: "catalog",
    vehicleIds: ["206-t5", "206-t2"],
    seller: {
      id: "s-eng",
      name: "قطعه گارانتی انقلاب",
      rating: 4.3,
      reviewCount: 64,
      neighborhood: "انقلاب",
      city: "تهران",
      distanceKm: 12.4,
      channel: "hybrid",
      hours: "۱۰ تا ۲۱",
      phone: "۰۲۱۶۶۴۴۰۰۱۲",
      hasInstallments: true,
      torobGuarantee: false,
      stock: "unknown",
      responseMins: 30,
    },
    deliveryHours: 24,
    actions: ["buy", "call"],
  },
  {
    id: "o8",
    title: "دیسک صفحه ۲۰۶ ارزان",
    brand: "بدون برند",
    origin: "aftermarket",
    price: 11_800_000,
    image: null,
    photoKind: "missing",
    vehicleIds: [],
    seller: {
      id: "s-digi",
      name: "دیجی‌یدک",
      rating: 3.9,
      reviewCount: 2104,
      neighborhood: "ارسال سراسری",
      city: "ایران",
      distanceKm: null,
      channel: "online",
      hasInstallments: true,
      torobGuarantee: false,
      stock: "now",
      responseMins: 120,
    },
    deliveryHours: 72,
    actions: ["buy"],
  },
  {
    id: "o9",
    title: "کیت کلاچ اصلی والئو جعبه‌دار",
    brand: "Valeo",
    origin: "oem",
    oemCode: "۸۲۶۲۱۱",
    price: 14_200_000,
    image: "/parts/oem-box.jpg",
    photoKind: "seller",
    vehicleIds: ["206-t5"],
    seller: {
      id: "s-coop",
      name: "تعاونی مکانیک پونک",
      rating: 4.5,
      reviewCount: 67,
      neighborhood: "پونک",
      city: "تهران",
      distanceKm: 1.5,
      channel: "hybrid",
      hours: "۸ تا ۱۷",
      phone: "۰۹۱۲۳۴۵۶۷۸۰",
      hasInstallments: true,
      torobGuarantee: true,
      stock: "limited",
      responseMins: 15,
    },
    deliveryHours: 4,
    actions: ["buy", "call", "nav", "chat"],
  },
  {
    id: "o10",
    title: "دیسک و صفحه کلاچ ۲۰۶",
    brand: "نامشخص",
    origin: "unknown",
    price: 15_500_000,
    image: null,
    photoKind: "missing",
    vehicleIds: [],
    seller: {
      id: "s-unknown",
      name: "یدکی برادران رضایی",
      rating: null,
      reviewCount: 0,
      neighborhood: "جنت‌آباد",
      city: "تهران",
      distanceKm: 8.2,
      channel: "physical",
      hours: "۹ تا ۱۸",
      phone: "۰۲۱۴۴۷۷۰۰۳۳",
      hasInstallments: false,
      torobGuarantee: false,
      stock: "unknown",
    },
    actions: ["call", "nav"],
  },
  {
    id: "o11",
    title: "کیت کلاچ والئو ۲۰۶ تیپ ۵",
    brand: "Valeo PHC",
    origin: "oem",
    price: 14_100_000,
    image: "/parts/valeo-box.jpg",
    photoKind: "catalog",
    vehicleIds: ["206-t5"],
    seller: {
      id: "s-karaj",
      name: "اتویدک گوهردشت",
      rating: 4.4,
      reviewCount: 41,
      neighborhood: "گوهردشت",
      city: "کرج",
      distanceKm: 32,
      channel: "hybrid",
      hours: "۹ تا ۲۰",
      phone: "۰۲۶۳۴۴۴۱۲۱۲",
      hasInstallments: false,
      torobGuarantee: true,
      stock: "now",
      responseMins: 20,
    },
    deliveryHours: 8,
    actions: ["buy", "call"],
  },
  {
    id: "o12",
    title: "دیسک و صفحه پراید ۱۳۱",
    brand: "ISKRA",
    origin: "aftermarket",
    price: 7_400_000,
    image: "/parts/aftermarket.jpg",
    photoKind: "catalog",
    vehicleIds: ["pride-131"],
    seller: {
      id: "s-pride",
      name: "پراید پارت تهران",
      rating: 4.4,
      reviewCount: 33,
      neighborhood: "شوش",
      city: "تهران",
      distanceKm: 18,
      channel: "physical",
      hours: "۹ تا ۱۸",
      phone: "۰۲۱۵۵۳۳۱۱۲۰",
      hasInstallments: false,
      torobGuarantee: false,
      stock: "now",
    },
    actions: ["call", "nav"],
  },
];

export const CATEGORIES = [
  { id: "clutch", label: "دیسک و صفحه", query: "دیسک صفحه ۲۰۶ تیپ ۵" },
  { id: "pads", label: "لنت ترمز", query: "لنت ترمز جلو ۲۰۶ تیپ ۵" },
  { id: "oil", label: "فیلتر روغن", query: "فیلتر روغن ۲۰۶ تیپ ۵" },
  { id: "spark", label: "شمع", query: "شمع TU5" },
  { id: "shock", label: "کمک فنر", query: "کمک فنر جلو ۲۰۶" },
  { id: "alt", label: "دینام", query: "دینام پژو ۲۰۶" },
  { id: "rad", label: "رادیاتور", query: "رادیاتور ۲۰۶ تیپ ۵" },
  { id: "timing", label: "تسمه تایم", query: "تسمه تایم TU5" },
];

export const NEARBY_RADIUS_KM = 5;
